Repository TimefoldAI/timefold-solver, pull requests merged in 2024-12, with the labels that each got.

#1243 chore: Remove GraalVM for Java 17 from Quarkus test, fix some warnings
  .github/workflows/pull_request.yml
  quarkus-integration/quarkus/devui-integration-test/pom.xml
  quarkus-integration/quarkus/integration-test/pom.xml
  quarkus-integration/quarkus/reflection-integration-test/pom.xml
  quarkus-integration/quarkus/runtime/pom.xml
Labels: build and release

#1249 fix: off-by-one error when choosing element locations
  core/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/list/ElementLocationRandomIterator.java
  core/src/test/java/ai/timefold/solver/core/impl/heuristic/selector/list/ElementDestinationSelectorTest.java
Labels: bug

#1250 feat: Add method to SolverConfig for setting unimproved spent limit termination
  core/src/main/java/ai/timefold/solver/core/config/solver/SolverConfig.java
  core/src/test/java/ai/timefold/solver/core/config/solver/SolverConfigTest.java
Labels: enhancement
